### ISSUE TITLE
Code Challenge: Response Could Not Be Evaluated

### ISSUE THREAD

**Issue by kaylee42** [learn-co-curriculum/enumerator-coding-challenge#12]
Just an FYI (I really have no idea what's wrong) that when I attempt to solve the code challenges I get a message that says "Response could not be evaluated. Please try again later." I get this on every challenge and received it both today and yesterday. I use Google Chrome and haven't had any technical problems like this on Learn besides this instance. I included a screenshot just so you can see what's up!
![screen shot 2015-10-18 at 9 49 18 pm](https://cloud.githubusercontent.com/assets/14985351/10568167/6d9ff734-75e2-11e5-90b4-ab76cf04cbdc.png)

**Comment by ktravers** [comment]
@kaylee42 Thanks for reporting. This issue has been closed with #4725. All code challenges should be working for you now.
