### ISSUE TITLE
Submitted code snipits are not being evaluated

### ISSUE THREAD

**Issue by JoanBrownCS** [learn-co-curriculum/enumerator-coding-challenge#14]
I am able to type in the code, but when I click to have the code evaluated, I get an error:
![image](https://cloud.githubusercontent.com/assets/15305066/11611035/b50d3cf4-9b75-11e5-9612-2b9274f6e2c7.png)

When I click to see the solution, nothing happens.
:( Sad day!

**Comment by zacscodingclub** [comment]
I'm having a similar experience.  I opened up Chrome's console, I see there appears to be an error connecting to repli.it.  I think this evaluates our input when we click the Submit button.

<img width="986" alt="screen shot 2015-12-12 at 3 59 45 pm" src="https://cloud.githubusercontent.com/assets/7807203/11764126/6d22389e-a0e9-11e5-8403-dec3e494f85f.png">

**Comment by AnnJohn** [comment]
Hi @JoanBrownCS and @zacscodingclub thanks for raising this. Since this is a bug report, can you submit a bug report on Learn? Thanks!
