### ISSUE TITLE
LOOKING FOR KEYWORD END BUT...

### ISSUE THREAD

**Issue by jcadamsjc** [learn-co-curriculum/enumerator-coding-challenge#15]
?I believe code is correct for this first item in the CODE CHALLENGE but why asking for keyword END 

lunch_menu = ["pizza", "sandwhich", "sushi", "soup", "salad"]

def lunch_menu 
lunch_menu.each do |lunch_item|
lunch_item << "!"
end

**Comment by zacscodingclub** [comment]
You do need another `end`.  Both the .each block and the lunch_menu method should have an `end`.
i.e.

```
def lunch_menu
  lunch_menu.each do | lunch_item |
    lunch_item << "!"
  end
end
```
