### ISSUE TITLE
Question #1 seems bugged

### ISSUE THREAD

**Issue by jamcelr** [learn-co-curriculum/enumerator-coding-challenge#18]
My solution to the first question was marked as wrong, even though the expected result matches the result from my code.  I tested my code in IRB and it is correct.  As such, I think there may be something wrong with the rspec test.  Thank you.

<img width="611" alt="screen shot 2015-12-16 at 4 46 13 pm" src="https://cloud.githubusercontent.com/assets/15949020/11855122/497ec5c6-a416-11e5-9109-c720be5c04d9.png">

**Comment by gregmarquet** [comment]
It seems that there is a spelling problem.They are looking for sandwich to be spelled like this "sandwhich" so if you change the lunch_menu to match this spelling it will work.

**Comment by jamcelr** [comment]
Yeah, you're right.  The lunch_menu array, along with its elements/values, were supplied by the quiz, so it appears the rspec test for that problem has a misspelling.

**Comment by jmburges** [comment]
Thanks for catching this. We closed it with PR #19
