### ISSUE TITLE
Validation requires a misspelling

### ISSUE THREAD

**Issue by rnbronstein** [learn-co-curriculum/enumerator-coding-challenge#20]
Correct solution returns "expected ["pizza!", "sandwich!", "sushi!", "soup!", "salad!"] to equal ["pizza!", "sandwhich!", "sushi!", "soup!", "salad!"]"

Changing string "sandwich" in array lunch_menu allows user to pass code challenge.

**Comment by jmburges** [comment]
Thanks for catching this. We closed it with PR #19
