### ISSUE TITLE
Way to specific requirements on REPLS

### ISSUE THREAD

**Issue by aviflombaum** [learn-co-curriculum/enumerator-coding-challenge#21]
![Too Specific](https://dl.dropboxusercontent.com/s/a3licf40bxpa0vb/2015-12-19%20at%202.54%20PM.png)

Notice how it wants you to use exactly the correct variable names.

This solution:

``` ruby
lunch_menu.each do |food|
  food << "!"
end
```

Won't pass even though it's accurate.

@AnnJohn @jmburges I think we should deprecate all REPLs until we can build a better one.

**Comment by jmburges** [comment]
Issues was with the assert, not with the solution. Closed with PR #19
