### ISSUE TITLE
Typo in Enumerator Code Challenge

### ISSUE THREAD

**Issue by cklynch2** [learn-co-curriculum/enumerator-coding-challenge#24]
Hello Learn Curriculum Team!

There is a small typo in the first part of the enumerator code challenge (.each method). The test seems to be comparing the output to "sandwhich" instead of "sandwich," causing the correct solution to be marked incorrect.

Thanks!
-Claire

**Comment by jmburges** [comment]
Thanks for catching this. We closed it with PR #19
