### ISSUE TITLE
add a "leave this page" if backspace is pressed

### ISSUE THREAD

**Issue by iandevivi** [learn-co-curriculum/enumerator-coding-challenge#25]
I've nearly finished this quiz 3 times now, except I hit backspace when I think i'm in a text box but I'm not and go back a page.

**Comment by AnnJohn** [comment]
hi @iandevivi sorry for the issue that you're having. Since it looks like something that's technical and not related to the curriculum, can you actually file a bug report? If you hover over your profile pic in Learn, you'll see an option from a drop down menu to "Report a Bug." 

Thanks!
