### ISSUE TITLE
Problem with questions

### ISSUE THREAD

**Issue by pianistps** [learn-co-curriculum/enumerator-coding-challenge#27]
In the enumerators code challenge quiz there is a problem with the questions. They are being pushed in as an answer choice for each question instead of looking like questions they look like an answer choice.  Just thought you all should know since it makes it a little confusing. 

<img width="791" alt="screen shot 2016-06-09 at 6 05 03 pm" src="https://cloud.githubusercontent.com/assets/18711707/15949404/d66122be-2e6c-11e6-87ec-1ed037ac3cad.png">
<img width="768" alt="screen shot 2016-06-09 at 6 05 15 pm" src="https://cloud.githubusercontent.com/assets/18711707/15949408/dae9af18-2e6c-11e6-831d-4d5af8ea3040.png">

**Comment by gj** [comment]
Seems to have been solved here: https://github.com/learn-co-curriculum/enumerator-coding-challenge/commit/170fd1d89476ebf510f673d8e4b705dafe5b0ff6

cc: @ktravers
