### ISSUE TITLE
Code Challenge IV not responding to correct answer

### ISSUE THREAD

**Issue by markedwardmurray** [learn-co-curriculum/enumerator-coding-challenge#3]
I figured it out, but just this one question isn't coming through as "Correct!"

@ktravers

**Comment by ktravers** [comment]
@markedwardmurray looking into it!

**Comment by ktravers** [comment]
@markedwardmurray should be fixed now. there was 1 character of trailing whitespace in validation that threw off the whole thing :-1: 

soon i'll have a fix in that'll make these things much less sensitive to whitespace. they're way too brittle at the moment.

**Comment by markedwardmurray** [comment]
:stars:
